// Copyright 2021-2023 The Connect Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.2.0 with parameter "js_import_style=legacy_commonjs,import_extension=js"
// @generated from file test.proto (package test, syntax proto3)
/* eslint-disable */

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { fileDesc, messageDesc, serviceDesc } = require("@bufbuild/protobuf/codegenv1");
const { file_google_protobuf_wrappers } = require("@bufbuild/protobuf/wkt");

/**
 * Describes the file test.proto.
 */
const file_test = /*@__PURE__*/
  fileDesc("Cgp0ZXN0LnByb3RvEgR0ZXN0IhwKCkZvb1JlcXVlc3QSDgoGbnVtYmVyGAEgASgFIhoKC0Zvb1Jlc3BvbnNlEgsKA3N0chgBIAEoCTK2AwoPU25hcHNob3RTZXJ2aWNlEioKA0ZvbxIQLnRlc3QuRm9vUmVxdWVzdBoRLnRlc3QuRm9vUmVzcG9uc2USTAoKRGVwcmVjYXRlZBIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlGhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlIgOIAgESSwoMQ2xpZW50U3RyZWFtEhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUaHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUoARJLCgxTZXJ2ZXJTdHJlYW0SGy5nb29nbGUucHJvdG9idWYuSW50MzJWYWx1ZRocLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZTABEksKCkJpZGlTdHJlYW0SGy5nb29nbGUucHJvdG9idWYuSW50MzJWYWx1ZRocLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZSgBMAESQgoFY2xhc3MSGy5nb29nbGUucHJvdG9idWYuSW50MzJWYWx1ZRocLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZTJDChVTZWNvbmRTbmFwc2hvdFNlcnZpY2USKgoDRm9vEhAudGVzdC5Gb29SZXF1ZXN0GhEudGVzdC5Gb29SZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_wrappers]);

/**
 * Describes the message test.FooRequest.
 * Use `create(FooRequestSchema)` to create a new message.
 */
const FooRequestSchema = /*@__PURE__*/
  messageDesc(file_test, 0);

/**
 * Describes the message test.FooResponse.
 * Use `create(FooResponseSchema)` to create a new message.
 */
const FooResponseSchema = /*@__PURE__*/
  messageDesc(file_test, 1);

/**
 * @generated from service test.SnapshotService
 */
const SnapshotService = /*@__PURE__*/
  serviceDesc(file_test, 0);

/**
 * This service should be generated into a second file
 *
 * @generated from service test.SecondSnapshotService
 */
const SecondSnapshotService = /*@__PURE__*/
  serviceDesc(file_test, 1);


exports.file_test = file_test;
exports.FooRequestSchema = FooRequestSchema;
exports.FooResponseSchema = FooResponseSchema;
exports.SnapshotService = SnapshotService;
exports.SecondSnapshotService = SecondSnapshotService;
