// Copyright 2021-2023 The Connect Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.1.0 with parameter "js_import_style=legacy_commonjs"
// @generated from file connectrpc/eliza/v1/eliza.proto (package connectrpc.eliza.v1, syntax proto3)
/* eslint-disable */

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const {
  fileDesc,
  messageDesc,
  serviceDesc,
} = require("@bufbuild/protobuf/codegenv1");

/**
 * Describes the file connectrpc/eliza/v1/eliza.proto.
 */
const file_connectrpc_eliza_v1_eliza =
  /*@__PURE__*/
  fileDesc(
    "Ch9jb25uZWN0cnBjL2VsaXphL3YxL2VsaXphLnByb3RvEhNjb25uZWN0cnBjLmVsaXphLnYxIh4KClNheVJlcXVlc3QSEAoIc2VudGVuY2UYASABKAkiHwoLU2F5UmVzcG9uc2USEAoIc2VudGVuY2UYASABKAkiIwoPQ29udmVyc2VSZXF1ZXN0EhAKCHNlbnRlbmNlGAEgASgJIiQKEENvbnZlcnNlUmVzcG9uc2USEAoIc2VudGVuY2UYASABKAkiIAoQSW50cm9kdWNlUmVxdWVzdBIMCgRuYW1lGAEgASgJIiUKEUludHJvZHVjZVJlc3BvbnNlEhAKCHNlbnRlbmNlGAEgASgJMpkCCgxFbGl6YVNlcnZpY2USSgoDU2F5Eh8uY29ubmVjdHJwYy5lbGl6YS52MS5TYXlSZXF1ZXN0GiAuY29ubmVjdHJwYy5lbGl6YS52MS5TYXlSZXNwb25zZSIAEl0KCENvbnZlcnNlEiQuY29ubmVjdHJwYy5lbGl6YS52MS5Db252ZXJzZVJlcXVlc3QaJS5jb25uZWN0cnBjLmVsaXphLnYxLkNvbnZlcnNlUmVzcG9uc2UiACgBMAESXgoJSW50cm9kdWNlEiUuY29ubmVjdHJwYy5lbGl6YS52MS5JbnRyb2R1Y2VSZXF1ZXN0GiYuY29ubmVjdHJwYy5lbGl6YS52MS5JbnRyb2R1Y2VSZXNwb25zZSIAMAFiBnByb3RvMw",
  );

/**
 * Describes the message connectrpc.eliza.v1.SayRequest.
 * Use `create(SayRequestSchema)` to create a new message.
 */
const SayRequestSchema =
  /*@__PURE__*/
  messageDesc(file_connectrpc_eliza_v1_eliza, 0);

/**
 * Describes the message connectrpc.eliza.v1.SayResponse.
 * Use `create(SayResponseSchema)` to create a new message.
 */
const SayResponseSchema =
  /*@__PURE__*/
  messageDesc(file_connectrpc_eliza_v1_eliza, 1);

/**
 * Describes the message connectrpc.eliza.v1.ConverseRequest.
 * Use `create(ConverseRequestSchema)` to create a new message.
 */
const ConverseRequestSchema =
  /*@__PURE__*/
  messageDesc(file_connectrpc_eliza_v1_eliza, 2);

/**
 * Describes the message connectrpc.eliza.v1.ConverseResponse.
 * Use `create(ConverseResponseSchema)` to create a new message.
 */
const ConverseResponseSchema =
  /*@__PURE__*/
  messageDesc(file_connectrpc_eliza_v1_eliza, 3);

/**
 * Describes the message connectrpc.eliza.v1.IntroduceRequest.
 * Use `create(IntroduceRequestSchema)` to create a new message.
 */
const IntroduceRequestSchema =
  /*@__PURE__*/
  messageDesc(file_connectrpc_eliza_v1_eliza, 4);

/**
 * Describes the message connectrpc.eliza.v1.IntroduceResponse.
 * Use `create(IntroduceResponseSchema)` to create a new message.
 */
const IntroduceResponseSchema =
  /*@__PURE__*/
  messageDesc(file_connectrpc_eliza_v1_eliza, 5);

/**
 * ElizaService provides a way to talk to Eliza, a port of the DOCTOR script
 * for Joseph Weizenbaum's original ELIZA program. Created in the mid-1960s at
 * the MIT Artificial Intelligence Laboratory, ELIZA demonstrates the
 * superficiality of human-computer communication. DOCTOR simulates a
 * psychotherapist, and is commonly found as an Easter egg in emacs
 * distributions.
 *
 * @generated from service connectrpc.eliza.v1.ElizaService
 */
const ElizaService =
  /*@__PURE__*/
  serviceDesc(file_connectrpc_eliza_v1_eliza, 0);

exports.file_connectrpc_eliza_v1_eliza = file_connectrpc_eliza_v1_eliza;
exports.SayRequestSchema = SayRequestSchema;
exports.SayResponseSchema = SayResponseSchema;
exports.ConverseRequestSchema = ConverseRequestSchema;
exports.ConverseResponseSchema = ConverseResponseSchema;
exports.IntroduceRequestSchema = IntroduceRequestSchema;
exports.IntroduceResponseSchema = IntroduceResponseSchema;
exports.ElizaService = ElizaService;
